version: '2'
services:
    web:
        image: nginx
        hostname: myapp.test
        ports:
            - "80:80"
        volumes:
            - ./app:/app
            - ./bin/conf/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - code-network
    php:
        build: ./
        hostname: php
        volumes:
            - ./app:/app
        networks:
            - code-network
    mysql:
        image: mysql:5.7
        hostname: mysql
        container_name: mysql
        ports:
            - "6068:3306"
        volumes:
            - ./bin/datadir/mysql:/var/lib/mysql
        networks:
            - code-network
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker

networks:
    code-network:
        driver: bridge
